[package]
name = "gitserver3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.12", features = ["derive"]}
itertools = "0.10.3"
memmap = "0.7.0"
regex-syntax = {path = "../regex/regex-syntax"}
suffix = { path = "../suffix" }
walkdir = "2.3.2"
